### ISSUE TITLE
Sorting does not work as expected, sorting is not applied before pagination.

### ISSUE THREAD

**Issue by tobwiens** [ow2-proactive/scheduling#2467]
The sorting does not seem to be applied before the pagination. This should have been fixed in 7.3.0 (https://github.com/ow2-proactive/scheduling-portal/pull/270) . Try version = version: 7.3.1. 

![page1](https://cloud.githubusercontent.com/assets/6491363/13253486/9249c628-da3c-11e5-99c5-934a10c15714.png)

![pag2](https://cloud.githubusercontent.com/assets/6491363/13253491/9737bfe6-da3c-11e5-92d3-157af7519b2d.png)

![page3](https://cloud.githubusercontent.com/assets/6491363/13253492/9902fb60-da3c-11e5-86d7-944f0f03a425.png)

**Comment by mbenguig** [comment]
When sorting tasks from the scheduler web portal, mapToDBNamespace(..)  is called (by the Scheduler front-end) to convert the sorting criteria ('jobId', 'jobName',..) to the corresponding column names in the db. The first fix is to add 'jobId' and 'jobName' entries in "sortableTaskAttrMap" that were missing .. Moreover, since they are part of  the JobData table, we have to update the SchedulerDBManager query that targets TaskData (join).

**Comment by fviale** [comment]
With recent versions, sorting is still not applied before pagination.

**Comment by bamedro** [comment]
Fixed using GraphQL query.
