### ISSUE TITLE
Node timed out when trying to join resource manager

### ISSUE THREAD

**Issue by paraita** [ow2-proactive/scheduling#2646]
Starting a node from command line using the default config settings can result in the node timing out when trying to joining a remote resource manager.
The node is expected to join successfully the remote resource manager but instead waits  before timing out.

We can reproduce the issue by running the following (example) command:
`java -Dproactive.home=/opt/PWS -Djava.security.policy=/opt/PWS/config/security.java.policy-client -Dlog4j.configuration=file:/opt/PWS/config/log/node.properties -Dfile.encoding=UTF-8 -cp .:/opt/PWS/addons:/opt/PWS/addons/*:/opt/PWS/dist/lib/* org.ow2.proactive.resourcemanager.utils.RMNodeStarter -v STRIPPED_CRED -n SSH-grappe1-1 -s grappe1 -r pnp://rm-ip-adress:64738/ -w 2`

This command is typically what's being run by SSHInfrastructureV2 to deploy nodes on remote machines.

The issue doesn't appear if the proactive-node is used instead (still a problem with SSHInfrastructureV2).

The issue is reproducible with:
* release 7.16
* on GNU/Linux
* on a distributed system (Scheduler running on one machine, a remote node trying to run from another machine)

**Comment by paraita** [comment]
After further investigation, it appear the RMNodeStarter class is no longer getting the communication protocol from the config file. Since the proactive.communication.protocol has no value, the rmi protocol is used instead while the Resource Manager is listening on PNP (by default). This result in the node not able to join the RM.

**Comment by lpellegr** [comment]
I have a problem with the Workflow I am working on for a customer. It seems the root cause is the same as the one which has been reported by Paraita. 

ProActive nodes started using the class _RMNodeStarter_ seem to ignore properties put in _config/network/node.ini_. By default the proactive communication protocol used is RMI. 

Starting ProActive nodes with property _-Dproactive.communication=X_ is not enough since Tasks are forked by default. The workaround I have found for now is to specify the last ProActive property in the fork environment of *each* task...

**Comment by laurianed** [comment]
RMNodeStarter cannot find the config file because the value of environment variable named `PAResourceManagerProperties.RM_HOME` is wrong.
It appears that the emailnotification-addons is creating the error:

- if addon is located into addons folder, after launching the command `PAResourceManagerProperties.RM_HOME` will be `/opt/.`

- if addon is removed from the addons folder, `PAResourceManagerProperties.RM_HOME` will be `/opt/PWS` and configuration file successfully found

**Comment by fviale** [comment]
This email-notification addon has created many issues apparently :-)

**Comment by lpellegr** [comment]
Yeah, the same root for 2 issues. Apparently, _scheduler-api_ (and transitive dependencies) must never be added twice in the classpath of the scheduler, even by accident. The exclusion which has been applied in _emailnotification-addons_ should fix both. 

Too bad that the exclusion was not applied before release from last Tuesday.

**Comment by fviale** [comment]
To me it seems this release is a bit "corrupt"

**Comment by marcocast** [comment]
there is this pull request related to this issue https://github.com/ow2-proactive/emailnotification-addons/pull/3 . 2 reviews and we can see if things improve.

**Comment by lpellegr** [comment]
@fviale It seems the release was made by knowing the problem.

**Comment by fviale** [comment]
Indeed, but we thought the problem as more minor as it actually is

**Comment by lpellegr** [comment]
Yeah, always a bad idea to underestimate things.
