### ISSUE TITLE
Missing nested evaluation in the declaration of task variables

### ISSUE THREAD

**Issue by Aminelouati** [ow2-proactive/scheduling#3066]
To replicate the bug, follow these steps:
1- Open the studio and create a first groovy task1.  
2- Add a task variable to groovy task1 Var1=hello
3- Create a second groovy task2 that depends on groovy task1. 
4- Add a task variable to groovy task2 Var2=${Var1}world
5- Display the Var2 (println variables.get("Var2")) 
6- Output: ${Var1}world different to the expected one: helloworld

Note that this evaluation works for workflow variables !!

**Comment by mbenguig** [comment]
Not sure this is an issue, since declaring a variable at the task level, does not imply its propagation. Following the same logic, defining a variable at the job level (toto=A), and redefining it at the task level (toto=B) does not change anything in the other tasks (toto=A). You have to explicitly put/get values in the variables map within the task body.

**Comment by Aminelouati** [comment]
It is rather an improvement. Actually, variable propagation is effective only within the task implementation scope and not in the declaration of task variables. We need to overcome this limit to enable dynamic declaration of variables.

**Comment by fviale** [comment]
It is by design like this:
1) For a task variable, it is not possible to use the syntax ${varname} inside the xml task définition (not implemented)
2) even if that would be possible, your example tries to use a task variable ${Var1} which belongs to a parent task. This will never be possible.
