### ISSUE TITLE
Error while fetching jobs: 500 Server Error 

### ISSUE THREAD

**Issue by EnesKilicaslan** [ow2-proactive/scheduling#3140]
When I go to scheduler page, I have this error.

"Error while fetching jobs: 500 Server Error The call failed on the server; see server log for details"
And when I go to logs, I can see that there is an exception in SchedulerServiceImpl.executeGraphQLQuery method.
<img width="1280" alt="screen shot 2018-02-16 at 18 34 18" src="https://user-images.githubusercontent.com/16417117/36314725-c354a9c8-1346-11e8-82f4-bc6fb132fd00.png">

When I click Network button, this dialog opens

<img width="585" alt="screen shot 2018-02-16 at 17 43 44" src="https://user-images.githubusercontent.com/16417117/36312712-70cbc3c2-1340-11e8-901c-8dab800ecbc7.png">

**Comment by fviale** [comment]
Could you attach the fragment of the logs with this exception (for example 1000 lines around) ?

**Comment by EnesKilicaslan** [comment]
Here is the log file
[network_error.log](https://github.com/ow2-proactive/scheduling/files/1731820/network_error.log)

**Comment by fviale** [comment]
Thank you. By analysing the logs, it shows that the scheduling-api web application is not present. This is necessary in order to display jobs on the scheduler portal. You need to build the https://github.com/ow2-proactive/scheduling-api project, and link it to the scheduler as you did for the scheduler, rm and studio.
For example:
ln -s ~/git/scheduling-api/scheduling-api-http/build/libs/scheduling-api-7.36.0-SNAPSHOT.war ~/git/scheduling/dist/war/scheduling-api.war

**Comment by EnesKilicaslan** [comment]
Thank you for your help, but I am still getting the very same error. I attached the log file.
[scheduler.log](https://github.com/ow2-proactive/scheduling/files/1733672/scheduler.log)

**Comment by EnesKilicaslan** [comment]
This was my mistake, After spending a few days, I noticed that I am using wrong symbolic link.
Intead of linking to **_scheduling-api/scheduling-api-http/build/libs/scheduling-api-7.36.0-SNAPSHOT.war_**  , I was linking to **_/scheduling-api/build/libs/scheduling-api-7.36.0-SNAPSHOT.jar_**
